on:
  push:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Pull templates
        uses: actions/checkout@v4

      - name: Pull schemes
        run: |
          git clone https://github.com/tinted-theming/base16-schemes schemes
          rm -rf schemes/.git

      - name: Add custom schemes
        run: cp -v custom_schemes/* schemes/

      - name: Build themes
        uses: tinted-theming/base16-builder-go@v0.2.9
        with:
          path: schemes

      - name: Delete schemes
        run: rm -rf schemes

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate themes"
          default_author: user_info
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
